### ISSUE TITLE
Action queue actions with move get inserted a 1 in the resource slot for the action

### ISSUE THREAD

**Issue by harmbuisman** [Lux-AI-Challenge/Lux-Design-2022#115]
The engine converts the actions from a submitted action_queue to have a 1 in the resource type row when an action is move. E.g. [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 4, 0, 0, 0] becomes [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 4, 1, 0, 0]. 

This is confusing since the observation does not encode the submitted queue. Also the slot is reserved for resource type.

From what I learned is that it was meant for distance in an old design. It would be better to keep it at 0 if there is no intention to do anything with distance.

**Comment by StoneT2000** [comment]
fixed by #123
