### ISSUE TITLE
Build C++ starter kit

### ISSUE THREAD

**Issue by StoneT2000** [Lux-AI-Challenge/Lux-Design-2022#5]

**Comment by StoneT2000** [comment]
@themmj

**Comment by StoneT2000** [comment]
To test your agent against the python one


```
python luxai_runner/runner.py kits/python/main.py kits/cpp/main.out -v 2
```

**Comment by themmj** [comment]
@StoneT2000 I've gotten a basic project set up. Before i proceed, i want to make sure it's going in the right direction.

- there is a simple bash script that will build the binary here https://github.com/themmj/Lux-Design-2022/blob/main/kits/cpp/compile.sh
- if someone wants to add more source files they can simply add them to this list https://github.com/themmj/Lux-Design-2022/blob/main/kits/cpp/sources.cmake (automatic source file detection e.g. with globbing is strongly discouraged by the CMake team, so I'm keeping it explicit)
- I'm using the same json lib as last season
Next step is creating proper classes/structs for the input and output json data (e.g. actions) for validation, type safety and convenience.

Any feedback so far is welcome.

**Comment by StoneT2000** [comment]
Awesome so far. we'll also need to add a simple script that allows compiling binaries with docker (for kaggle submission) but everything else looks nice and clean!

Also note that I've recently more or less added all the core functionality to the python kit. Any feedback for that is welcome but otherwise try to add those functionalities and classes to the C++ kit.

**Comment by themmj** [comment]
Quick update. The kit is already somewhat usable. It is missing mostly convenience (e.g. canBuildHeavy and stuff like that) and documentation. Feel free to look around the code if you are interested: https://github.com/themmj/Lux-Design-2022
It's still prone to breaking changes though while I figure out a clean way for all the convenience stuff.

**Comment by themmj** [comment]
@StoneT2000 Good news, the kit is basically done code-wise. This is the code for a basic agent https://github.com/themmj/Lux-Design-2022/blob/main/kits/cpp/src/agent.cpp
It has full feature parity to the python kit (including stuff like the factory occupancy map etc.). The only thing it's missing now is documentation (build / submission instructions and code docs), but I don't think this is a priority at the moment.
As always, feedback is very welcome if you have any.

**Comment by StoneT2000** [comment]
Great work! I'll check it out this weekend most likely.

**Comment by StoneT2000** [comment]
@themmj oh can you make a PR?

**Comment by themmj** [comment]
Done: https://github.com/Lux-AI-Challenge/Lux-Design-2022/pull/45
