### ISSUE TITLE
Errors when trying to validate installation

### ISSUE THREAD

**Issue by harmbuisman** [Lux-AI-Challenge/Lux-Design-2022#67]
If I run the getting started steps from the manual I get the following error when trying to validate my installation:

Both using (https://github.com/Lux-AI-Challenge/Lux-Design-2022):
luxai2022 my_bot/main.py my_other_bot/main.py -v 2 -o replay.json

and (https://github.com/Lux-AI-Challenge/Lux-Design-2022/tree/main/kits/python)
luxai2022 main.py main.py --out=replay.json

Version info:
python                    3.7.13
luxai2022                 1.0.4

The errors are:
Task exception was never retrieved
future: <Task finished coro=<BotProcess.start() done, defined at DIR\Anaconda3\envs\lux\lib\site-packages\luxai_runner\process.py:33> exception=NotImplementedError()>
Traceback (most recent call last):
  File "DIR\Anaconda3\envs\lux\lib\site-packages\luxai_runner\process.py", line 47, in start
    limit=1024 * 128
  File "DIR\Anaconda3\envs\lux\lib\asyncio\subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "DIR\Anaconda3\envs\lux\lib\asyncio\base_events.py", line 1544, in subprocess_exec
    bufsize, **kwargs)
  File "DIR\Anaconda3\envs\lux\lib\asyncio\base_events.py", line 462, in **_make_subprocess_transport
    raise NotImplementedError
NotImplementedError**
Task exception was never retrieved
future: <Task finished coro=<BotProcess.start() done, defined at DIR\Anaconda3\envs\lux\lib\site-packages\luxai_runner\process.py:33> exception=NotImplementedError()>
Traceback (most recent call last):
  File "DIR\Anaconda3\envs\lux\lib\site-packages\luxai_runner\process.py", line 47, in start
    limit=1024 * 128
  File "DIR\Anaconda3\envs\lux\lib\asyncio\subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "DIR\Anaconda3\envs\lux\lib\asyncio\base_events.py", line 1544, in subprocess_exec
    bufsize, **kwargs)
  File "DIR\Anaconda3\envs\lux\lib\asyncio\base_events.py", line 462, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "DIR\Anaconda3\envs\lux\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "DIR\Anaconda3\envs\lux\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "DIR\Anaconda3\envs\lux\Scripts\luxai2022.exe\__main__.py", line 7, in <module>
  File "DIR\Anaconda3\envs\lux\lib\site-packages\luxai_runner\cli.py", line 83, in main
    asyncio.run(eps.run())
  File "DIR\Anaconda3\envs\lux\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "DIR\Anaconda3\envs\lux\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "DIR\Anaconda3\envs\lux\lib\site-packages\luxai_runner\episode.py", line 109, in run
    resolved_actions = await asyncio.gather(*action_coros)
  File "DIR\Anaconda3\envs\lux\lib\site-packages\luxai_runner\bot.py", line 54, in step
    action, stderr = await asyncio.wait_for(self.proc.write(f"{data}\n"), timeout=self.remainingOverageTime + self.time_per_step)
  File "DIR\Anaconda3\envs\lux\lib\asyncio\tasks.py", line 442, in wait_for
    return fut.result()
  **File "DIR\Anaconda3\envs\lux\lib\site-packages\luxai_runner\process.py", line 72, in write
    self._agent_process.stdin.write(msg.encode())
AttributeError: 'BotProcess' object has no attribute '_agent_process'**

**Comment by StoneT2000** [comment]
Can you verify the files you passed in are correct paths? Otherwise it might print this kindof error.

**Comment by Logan9312** [comment]
I'm getting an issue trying to run luxai2022 my_bot/main.py my_other_bot/main.py -v 2 -o replay.json as well. Here is my output:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Scripts\luxai2022.exe\__main__.py", line 4, in <module>
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Lib\site-packages\luxai_runner\cli.py", line 3, in <module>
    from luxai_runner.bot import Bot
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Lib\site-packages\luxai_runner\bot.py", line 9, in <module>
    from luxai_runner.logger import Logger
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Lib\site-packages\luxai_runner\logger.py", line 3, in <module>
    from luxai2022.globals import TERM_COLORS
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Lib\site-packages\luxai2022\__init__.py", line 1, in <module>
    from .env import LuxAI2022
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Lib\site-packages\luxai2022\env.py", line 7, in <module>
    from pettingzoo import ParallelEnv
ImportError: cannot import name 'ParallelEnv' from 'pettingzoo' (C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Lib\site-packages\pettingzoo\__init__.py)`

**Comment by harmbuisman** [comment]
I retried with copying the kit files also to the same directory, but get the same errors. 
Note though that the manual does not say anything about needing folders with main.py files, so perhaps that should be added as well. 

The manual says do these 2 things:
`pip install --upgrade luxai2022`
`luxai2022 my_bot/main.py my_other_bot/main.py -v 2 -o replay.json`

I guess it makes sense that there should be a folder my_bot and my_other_bot somewhere, but then it should be added as a step how to populate those. Also I would expect a meaningful error in that case.

**Comment by StoneT2000** [comment]
I see, I think it's not super obvious that `my_bot/main.py my_other_bot/main.py` should be your own defined paths, I've made an issue for this #71

**Comment by StoneT2000** [comment]
So is any of the local code working?

If you git clone this repository and run 

```
luxai2022 kits/python/main.py kits/python/main.py -v 2 -o replay.json
```
what happens?

**Comment by harmbuisman** [comment]
I get the same error with that call. I would also expect the call to search for the files relative to the directory I am calling from. So this requires me to call from the base package folder I guess. In that case that could be added to the docs.

E.g. if I would move into the kits/python directory I should be calling 
`luxai2022 main.py main.py -v 2 -o replay.json`

correct?
That call gives the same error btw. Perhaps there is something wrong with my package versions

**Comment by StoneT2000** [comment]
Yep if you move to kits/python that call is correct.

Can you print your python version and also print the versions of all the packages? Lastly what’s is your system / os?

**Comment by Logan9312** [comment]
Attempting to call the bots gives me this error (windows 11)

```py
$ luxai2022 kits/python/main.py kits/python/main.py -v 2 -o replay.json
Traceback (most recent call last):
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\Scripts\luxai2022.exe\__main__.py", line 7, in <module>
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\site-packages\luxai_runner\cli.py", line 83, in main
    asyncio.run(eps.run())
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\site-packages\luxai_runner\episode.py", line 109, in run
    resolved_actions = await asyncio.gather(*action_coros)
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\site-packages\luxai_runner\bot.py", line 53, in step
    data = json.dumps(observations)
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int32 is not JSON serializable
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000022F511A3640>
Traceback (most recent call last):
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 126, in __del__
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000022F511A3640>
Traceback (most recent call last):
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 126, in __del__
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022F511C9120>
Traceback (most recent call last):
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022F511C9120>
Traceback (most recent call last):
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022F511C9120>
Traceback (most recent call last):
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022F511C9120>
Traceback (most recent call last):
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed```

**Comment by harmbuisman** [comment]
Python 3.7.13
Windows OS

Name                    Version                   Build  Channel
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.5.0            py37haa95532_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0           py37h2bbff1b_0
astroid                   2.12.12                  pypi_0    pypi
attrs                     21.4.0             pyhd3eb1b0_0
babel                     2.9.1              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
beautifulsoup4            4.11.1           py37haa95532_0
black                     22.10.0                  pypi_0    pypi
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
bottleneck                1.3.5            py37h080aedc_0
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotlipy                  0.7.0           py37h2bbff1b_1003
ca-certificates           2022.10.11           haa95532_0
certifi                   2022.9.24        py37haa95532_0
cffi                      1.15.1           py37h2bbff1b_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.3                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
cryptography              38.0.1           py37h21b164f_0
cycler                    0.11.0             pyhd3eb1b0_0
debugpy                   1.5.1            py37hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
dill                      0.3.6                    pypi_0    pypi
entrypoints               0.4              py37haa95532_0
ffmpeg                    4.2.2                he774522_0
flake8                    5.0.4                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
glib                      2.69.1               h5dc1a3c_1
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
gym                       0.19.0                   pypi_0    pypi
gymnasium                 0.26.3                   pypi_0    pypi
gymnasium-notices         0.0.1                    pypi_0    pypi
icu                       58.2                 ha925a31_3
idna                      3.4              py37haa95532_0
imageio                   2.19.3           py37haa95532_0
imageio-ffmpeg            0.4.7              pyhd8ed1ab_0    conda-forge
importlib-metadata        5.0.0                    pypi_0    pypi
importlib_metadata        4.11.3               hd3eb1b0_0
importlib_resources       5.2.0              pyhd3eb1b0_1
intel-openmp              2021.4.0          haa95532_3556
ipykernel                 6.15.2           py37haa95532_0
ipython                   7.31.1           py37haa95532_1
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.5              pyhd3eb1b0_1
isort                     5.10.1                   pypi_0    pypi
jedi                      0.18.1           py37haa95532_1
jinja2                    3.1.2            py37haa95532_0
jpeg                      9e                   h2bbff1b_0
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                4.16.0           py37haa95532_0
jupyter                   1.0.0            py37haa95532_8
jupyter_client            7.3.5            py37haa95532_0
jupyter_console           6.4.3              pyhd3eb1b0_0
jupyter_core              4.11.1           py37haa95532_0
jupyter_server            1.18.1           py37haa95532_0
jupyterlab                3.4.4            py37haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.15.2           py37haa95532_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
kiwisolver                1.4.4                    pypi_0    pypi
lazy-object-proxy         1.8.0                    pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  12.0.0          default_h627e005_2
libdeflate                1.8                  h2bbff1b_5
libffi                    3.4.2                hd77b12b_4
libiconv                  1.16                 h2bbff1b_2
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libtiff                   4.4.0                h8a3f274_1
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.4                h2bbff1b_0
libwebp-base              1.2.4                h2bbff1b_0
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
luxai2022                 1.0.4                    pypi_0    pypi
lz4-c                     1.9.3                h2bbff1b_1
markupsafe                2.1.1            py37h2bbff1b_0
matplotlib-base           3.5.3            py37hd77b12b_0
matplotlib-inline         0.1.6            py37haa95532_0
mccabe                    0.7.0                    pypi_0    pypi
mistune                   0.8.4           py37hfa6e2cd_1001
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py37h2bbff1b_0
mkl_fft                   1.3.1            py37h277e83a_0
mkl_random                1.2.2            py37hf11a4ad_0
moviepy                   1.0.3              pyhd8ed1ab_1    conda-forge
munkres                   1.1.4                      py_0
mypy-extensions           0.4.3                    pypi_0    pypi
nbclassic                 0.3.5              pyhd3eb1b0_0
nbclient                  0.5.13           py37haa95532_0
nbconvert                 6.4.4            py37haa95532_0
nbformat                  5.5.0            py37haa95532_0
nest-asyncio              1.5.5            py37haa95532_0
notebook                  6.4.12           py37haa95532_0
numexpr                   2.8.3            py37hb80d3ca_0
numpy                     1.21.6                   pypi_0    pypi
numpy-base                1.21.5           py37hca35cd5_3
omegaconf                 2.2.3                    pypi_0    pypi
openssl                   1.1.1q               h2bbff1b_0
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.3.5            py37h6214cd6_0
pandocfilters             1.5.0              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pathspec                  0.10.1                   pypi_0    pypi
pcre                      8.45                 hd77b12b_0
pettingzoo                1.22.1                   pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.3.0                    pypi_0    pypi
pip                       22.2.2           py37haa95532_0
pkgutil-resolve-name      1.3.10           py37haa95532_0
platformdirs              2.5.2                    pypi_0    pypi
ply                       3.11                     py37_0
proglog                   0.1.9                      py_0    conda-forge
prometheus_client         0.14.1           py37haa95532_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
prompt_toolkit            3.0.20               hd3eb1b0_0
psutil                    5.9.0            py37h2bbff1b_0
pycodestyle               2.9.1                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pyflakes                  2.5.0                    pypi_0    pypi
pygame                    2.1.2                    pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0
pylint                    2.15.5                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9            py37haa95532_0
pyqt                      5.15.7           py37hd77b12b_0
pyqt5-sip                 12.11.0          py37hd77b12b_0
pyrsistent                0.18.0           py37h196d8e1_0
pysocks                   1.7.1                    py37_1
python                    3.7.13               h6244533_1
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2           py37haa95532_0
pytz                      2022.1           py37haa95532_0
pywin32                   302              py37h2bbff1b_2
pywinpty                  2.0.2            py37h5da7b33_0
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     23.2.0           py37hd77b12b_0
qt-main                   5.15.2               he8e5bd7_7
qt-webengine              5.15.9               hb9a9bb5_4
qtconsole                 5.3.2            py37haa95532_0
qtpy                      2.2.0            py37haa95532_0
qtwebkit                  5.212                h3ad3cdb_4
requests                  2.28.1           py37haa95532_0
scipy                     1.7.3                    pypi_0    pypi
seaborn                   0.12.0           py37haa95532_0
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                65.5.0           py37haa95532_0
sip                       6.6.2            py37hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.2.0            py37haa95532_1
soupsieve                 2.3.2.post1      py37haa95532_0
sqlite                    3.39.3               h2bbff1b_0
termcolor                 2.1.0                    pypi_0    pypi
terminado                 0.13.1           py37haa95532_0
testpath                  0.6.0            py37haa95532_0
tk                        8.6.12               h2bbff1b_0
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1                    pypi_0    pypi
tomlkit                   0.11.6                   pypi_0    pypi
tornado                   6.2              py37h2bbff1b_0
tqdm                      4.64.1           py37haa95532_0
traitlets                 5.1.1              pyhd3eb1b0_0
typed-ast                 1.5.4                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
typing_extensions         4.3.0            py37haa95532_0
urllib3                   1.26.12          py37haa95532_0
vc                        14.2                 h21ff451_1
vec-noise                 1.1.4                    pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1                    py37_1
websocket-client          0.58.0           py37haa95532_4
wheel                     0.37.1             pyhd3eb1b0_0
widgetsnbextension        3.5.2            py37haa95532_0
win_inet_pton             1.1.0            py37haa95532_0
wincertstore              0.2              py37haa95532_2
winpty                    0.4.3                         4
wrapt                     1.14.1                   pypi_0    pypi
xz                        5.2.6                h8cc25b3_0
zeromq                    4.3.4                hd77b12b_0
zipp                      3.10.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.2                h19a0ad4_0

**Comment by StoneT2000** [comment]
> Attempting to call the bots gives me this error (windows 11)
> 
> ```python
> $ luxai2022 kits/python/main.py kits/python/main.py -v 2 -o replay.json
> Traceback (most recent call last):
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\Scripts\luxai2022.exe\__main__.py", line 7, in <module>
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\site-packages\luxai_runner\cli.py", line 83, in main
>     asyncio.run(eps.run())
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
>     return future.result()
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\site-packages\luxai_runner\episode.py", line 109, in run
>     resolved_actions = await asyncio.gather(*action_coros)
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\site-packages\luxai_runner\bot.py", line 53, in step
>     data = json.dumps(observations)
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 231, in dumps
>     return _default_encoder.encode(obj)
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
>     return _iterencode(o, 0)
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
>     raise TypeError(f'Object of type {o.__class__.__name__} '
> TypeError: Object of type int32 is not JSON serializable
> Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000022F511A3640>
> Traceback (most recent call last):
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 126, in __del__
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 104, in close
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000022F511A3640>
> Traceback (most recent call last):
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 126, in __del__
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 104, in close
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022F511C9120>
> Traceback (most recent call last):
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022F511C9120>
> Traceback (most recent call last):
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022F511C9120>
> Traceback (most recent call last):
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022F511C9120>
> Traceback (most recent call last):
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
>   File "C:\Users\lgntr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
> RuntimeError: Event loop is closed
> ```

It appears multiple people have the same bug on windows (two others mentioned the same bug on windows).

**Comment by StoneT2000** [comment]
@harmbuisman @Logan9312 can both of install `pip install luxai2022==1.0.5`. I know for @Logan9312 this should fix your bug, but it may also fix yours @harmbuisman .

**Comment by Logan9312** [comment]
This worked, thanks!

**Comment by harmbuisman** [comment]
@StoneT2000 

It gives me the same error.

I did some debugging and the following call in process.py fails:
```
        self._agent_process = await asyncio.create_subprocess_exec(
            self.command,
            os.path.basename(self.file_path),
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=cwd,
            limit=1024 * 128,
        )
```

I verified the self.file_path exists from the code.

Looking around on StackOverflow I found this is a known issue with Python 3.7:
https://stackoverflow.com/questions/53127248/asyncio-create-subprocess-shell-python-3-7-on-windows

**Comment by StoneT2000** [comment]
@harmbuisman could you try python 3.8? Let me know if it still fails

**Comment by harmbuisman** [comment]
> luxai2022 main.py main.py -v 2 -o replay.json

With Python 3.8 the game runs when specifying an existing path, which is good!


I do see a whole lot of errors at the end with a message they are ignored:
```
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000002370A3745E0>
Traceback (most recent call last):
  File "C:\Users\HBU1808.39421\Anaconda3\envs\lux_test\lib\asyncio\base_subprocess.py", line 126, in __del__
    self.close()
  File "C:\Users\HBU1808.39421\Anaconda3\envs\lux_test\lib\asyncio\base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "C:\Users\HBU1808.39421\Anaconda3\envs\lux_test\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\HBU1808.39421\Anaconda3\envs\lux_test\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\HBU1808.39421\Anaconda3\envs\lux_test\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
```

If I provide a path that does not exist, I still get the error as in the first post. So perhaps it would be good to add a validation for the existence of the path before creating the subprocess.

**Comment by StoneT2000** [comment]
this may somehow be related to #80 , there just seems to be multiple errors being reported on windows machines when using the `asyncio` package. If you want to avoid them you can follow the tutorial kit which provides a `interact` function to run a single game, and you can edit that as you see fit.
