### ISSUE TITLE
Factories can overlap

### ISSUE THREAD

**Issue by harmbuisman** [Lux-AI-Challenge/Lux-Design-2022#72]
It is possible to build factories that overlap. 
![image](https://user-images.githubusercontent.com/7702207/199741673-fbf22a6a-4969-4f26-8b02-f6d33e2bc013.png)

I think this should lead to an error instead?

**Comment by StoneT2000** [comment]
Yes, this issue was raised earlier, thanks for making a GitHub issue out of this!

This should not be allowed in any way in our environment so if you use this as a strategy be aware that it will be invalid in the future.
