### ISSUE TITLE
Game ends at game turn 996

### ISSUE THREAD

**Issue by harmbuisman** [Lux-AI-Challenge/Lux-Design-2022#81]
The game ends at real_env_steps==996. I expected the pre-phase iterations not to count as steps for the action play so that the game ends at 1000 instead.

What do you think?

<img width="580" alt="image" src="https://user-images.githubusercontent.com/7702207/200172054-f05b25c5-296b-4e6a-a520-bee7ce9f774d.png">

**Comment by StoneT2000** [comment]
Did one teams factories all disappear?

**Comment by StoneT2000** [comment]
Aware of this bug now, this is because kaggle competition servers truncates episodes to 1000 steps total, but our environment has 1000 + N steps where N varies. Will fix soon!
