### ISSUE TITLE
Cost to water lichen is incorrectly calculated

### ISSUE THREAD

**Issue by AmonUCF** [Lux-AI-Challenge/Lux-Design-2022#98]
https://github.com/Lux-AI-Challenge/Lux-Design-2022/blob/f20bbfafbeebc3c1effe42ba248674240a6f3aab/luxai2022/factory.py#L111

From the spec, the formula for computing cost to water is: "ceil(# connected lichen tiles / 10)". The formula here is adding 1 to the end of the computation. I suspect the reason for this was because without the +1, the first time you water a factory it would cost 0 water (due to there being no connected lichen tiles). 

I suggest modifying the formula to be:
1, if no connected lichen tiles
ceil(# connected lichen tiles / 10), if #connected lichen tiles > 0

**Comment by StoneT2000** [comment]
fixed!
